name: build-and-deploy

on:
push:
branches:
- main

jobs:
build-and-deploy:
runs-on: ubuntu-latest

permissions:
  contents: write
  pages: write

steps:
  - name: Checkout Repository
    uses: actions/checkout@v3

  - name: Inject Firebase Config
    run: |
      sed -i "s|const firebaseConfig = {.*};|const firebaseConfig = JSON.parse(atob('\${{ secrets.FIREBASE_CONFIG }}'));|" index.html
      sed -i "s|const appId = '.*';|const appId = '\${{ secrets.APP_ID }}';|" index.html
      sed -i "s|const initialAuthToken = '.*';|const initialAuthToken = '\${{ secrets.INITIAL_AUTH_TOKEN }}';|" index.html

  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./
      keep_files: false
      force_orphan: true
