name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Inject Firebase Config
        run: |
          sed -i "s|<!-- FIREBASE_CONFIG_PLACEHOLDER -->|<script>const firebaseConfig = JSON.parse(atob('${{ secrets.FIREBASE_CONFIG_BASE64 }}')); const appId = '${{ secrets.APP_ID }}'; const initialAuthToken = '${{ secrets.AUTH_TOKEN }}';</script>|g" index.html
        env:
          FIREBASE_CONFIG_BASE64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
          APP_ID: ${{ secrets.APP_ID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
