name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Inject Firebase Config
        run: |
          sed -i "s|const firebaseConfig = typeof __firebase_config !== 'undefined' ? JSON.parse(__firebase_config) : null;|const firebaseConfig = '${{ secrets.FIREBASE_CONFIG }}';|g" index.html
          sed -i "s|const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';|const appId = '${{ secrets.APP_ID }}';|g" index.html
          sed -i "s|const initialAuthToken = typeof __initial_auth_token !== 'undefined' ? __initial_auth_token : null;|const initialAuthToken = '${{ secrets.AUTH_TOKEN }}';|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
